name = "CorrelEq"
uuid = "d8fd485f-4c4b-4cfa-b507-2290d128bc2e"
authors = ["Mckay Jensen"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
